server:
  error:
    include-message: always
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your google client id
            client-secret: your google clientsecret
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs